spring:
  application:
    name: zuul-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.143.130:3306/zuul-server
    username: root
    password: zhanwei
  cloud:
    consul:
      host: 121.42.143.130
      port: 8500
      enabled: true
      discovery:
        health-check-path: /actuator/health

### 日志级别
logging:
  level:
    ROOT: info


######### Token相关配置
### secret 计算token用到的签名
### header 客户端发起请求时，Token对应的key值
### salt token的前缀
security:
  secret: https://github.com/hzwy23
  header: Authorization
  salt: "Bearer "

cassandra:
  host: 118.31.46.174
  keyspace: gateway
  port: 9042
