spring:
  application:
    name: zuul-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.143.130:3306/zuul-server
    username: root
    password: zhanwei
  cloud:
    consul:
      host: 121.42.143.130
      port: 8500
      enabled: true
      discovery:
        health-check-path: /system/actuator/health
        prefer-ip-address: true
        ip-address: 182.254.165.72
  ### 调用追踪配置
  zipkin:
    base-url: http://localhost:9410
  sleuth:
    sampler:
      percentage: 1.0

### 日志级别
logging:
  level:
    ROOT: info

cassandra:
  host: 121.42.143.130
  keyspace: gateway
  port: 9042
